[build]
  command = "cd Tesla-Back/TeslaSpringBoot && ./mvnw clean package"

[service]
  name = "tesla-backend"
  path = "Tesla-Back/TeslaSpringBoot"
  dockerfile = "Tesla-Back/TeslaSpringBoot/Dockerfile"
  start_command = "java -jar /app.jar"
  port = 8080

